require('dotenv').config();
require('./server/db-conn');
const express = require('express');
const bodyParser = require('body-parser');
const index = require('./server/routes/index');
const cors = require('cors')


const app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cors(corsOption = {
  origin: true,
  methods: 'GET,HEAD,PUT,PATCH,POST,DELETE',
  credentials: true,
  exposedHeaders: ['x-auth-token']
}))
// gives server access to static files generated by running yarn build in client
app.use(express.static('./client/loggingapp/build/'));

// mount routes
// app.use('/api/thoughts/', require('./server/routes/thoughts-route'));
app.use('/api', index);

// the asterisk is very important!! as it allows client side routing
// with react-router or w/e client side routing package you use
app.get('/*', (req, res) => {
  res.sendFile('index.html', { root: __dirname + '/client/loggingapp/build/' });
});

const { PORT } = process.env;
app.listen(PORT, () => console.log(`Wizardry happening on port ${PORT}`));